# where to download dataset
dataset_url = 'https://raw.githubusercontent.com/paras42/Hello_World_Deep_Learning/master/Open_I_abd_vs_CXRs.zip'
dataset_directory_name = 'Open_I_abd_vs_CXRs'

# dimensions of our images
img_width = 299
img_height = 299

# directory and image information
train_data_dir = 'Open_I_abd_vs_CXRs/TRAIN'
validation_data_dir = 'Open_I_abd_vs_CXRs/VAL'

train_samples = 65
validation_samples = 10

epochs = 20 # number of passes of through training data
batch_size = 5 # number images processed at same time

# data augmentation
rescale=0.003921568627 # = 1/255 (Rescale pixel values to 0-1 to aid CNN processing)
shear_range=0.2  # 0-1 range for shearing
zoom_range=0.2  # 0-1 range for zoom
rotation_range=20  # 0-180 range, degrees of rotation
width_shift_range=0.2  # 0-1 range horizontal translation
height_shift_range=0.2  # 0-1 range vertical translation
horizontal_flip = true  # set True or False)
